# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_auto_20170625_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='borrow_data',
            fields=[
                ('Chargehist_User_Id', models.CharField(max_length=255)),
                ('Chargehist_User_Name', models.CharField(max_length=255)),
                ('History_Title', models.CharField(max_length=255)),
                ('studentID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('college', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('peopleKind', models.CharField(max_length=255)),
            ],
        ),
    ]
