# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_borrow_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='book_edge',
            fields=[
                ('book_1', models.CharField(max_length=255)),
                ('book_2', models.CharField(max_length=255)),
                ('History_Title', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('book_3', models.CharField(max_length=255)),
            ],
        ),
    ]
